name: Endor Labs Dependency and Secrets Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  scan:
    permissions:
      id-token: write
      repository-projects: read
      pull-requests: read
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Build Package
      run: mvn clean install
    - name: Endor Labs Scan
      uses: endorlabs/github-action@v1.1.1
      with:
        namespace: 'nate-learn'
        scan_dependencies: true
        scan_secrets: true
        # pr: true
        # enable_pr_comments: ${{ env.ENDORCTL_PR }}
        # github_token: ${{ secrets.GITHUB_TOKEN }} # Required for PR comments on new policy violations
        sarif_file: 'findings.sarif'
        log_level: debug
        log_verbose: true
      continue-on-error: true
    - name: Show Directory
      run: "ls"
          
  # scan-main:
  #   permissions:
  #     id-token: write
  #     repository-projects: read
  #     pull-requests: read
  #     contents: read
  #   name: endorctl-scan
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: 'Endor Labs Scan Push to main'
  #     if: ${{ github.event_name == 'push' }}
  #     uses: endorlabs/github-action@v1.1.1
  #     with:
  #       namespace: 'example' # Replace with your Endor Labs tenant namespace
  #       scan_dependencies: true
  #       scan_secrets: true
  #       pr: false
  #       scan_summary_output_type: 'table'
  #       sarif_file: 'findings.sarif'
  #   - name: Upload findings to github
  #     uses: github/codeql-action/upload-sarif@9885f86fab4879632b7e44514f19148225dfbdcd
  #     with:
  #       sarif_file: 'findings.sarif'
